"""
CLI entry point. Outer game loop — win/loss checks live here.

The graphs are split at the player-input point:
  pre-turn  → display screen → get input → post-turn → display consequences → repeat

Modes:
  (default)        Classic mode — authored crises, numbered menu choices
  --mode freeform  Freeform mode — LLM-generated crises, free-text responses
"""

import sys
import game.config as cfg

# ── CLI flags ─────────────────────────────────────────────────────────────────

if "--debug" in sys.argv:
    cfg.DEBUG = True

if "--list-scenarios" in sys.argv:
    from game.scenarios import list_scenarios
    list_scenarios()
    sys.exit(0)

if "--scenario" in sys.argv:
    idx = sys.argv.index("--scenario")
    if idx + 1 >= len(sys.argv) or sys.argv[idx + 1].startswith("--"):
        print("Error: --scenario requires a name. Use --list-scenarios to see options.")
        sys.exit(1)
    from game.scenarios import apply_scenario
    apply_scenario(sys.argv[idx + 1])

_mode = "classic"
if "--mode" in sys.argv:
    idx = sys.argv.index("--mode")
    if idx + 1 < len(sys.argv) and not sys.argv[idx + 1].startswith("--"):
        _mode = sys.argv[idx + 1]
    if _mode not in ("classic", "freeform"):
        print(f"Error: unknown mode '{_mode}'. Available: classic, freeform")
        sys.exit(1)

if "--graph" in sys.argv:
    from graph.game_graph import save_graph_image
    idx = sys.argv.index("--graph")
    output = (
        sys.argv[idx + 1]
        if idx + 1 < len(sys.argv) and not sys.argv[idx + 1].startswith("--")
        else "graph.png"
    )
    save_graph_image(output)
    sys.exit(0)

# ── Imports (after scenario patch, before graph compilation) ──────────────────

from dotenv import load_dotenv
load_dotenv()

from cli.display import (
    console,
    display_consequences,
    display_end_screen,
    display_freeform_consequences,
    display_freeform_turn_screen,
    display_loss_screen,
    display_start_screen,
    display_turn_screen,
)
from game.engine import check_loss, determine_end_state
from game.scenarios import get_active_scenario
from graph.nodes import generate_end_summary, initialize_game

if _mode == "freeform":
    from graph.freeform_graph import pre_freeform_graph, post_freeform_graph
else:
    from graph.game_graph import pre_classic_graph, post_classic_graph


# ── CLI input helpers ─────────────────────────────────────────────────────────

def _get_classic_choice(state: dict) -> int:
    options = state["active_crisis"]["options"]
    while True:
        raw = input(f"\n  Your choice [1–{len(options)}]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return int(raw) - 1
        print(f"  Please enter a number between 1 and {len(options)}.")


def _get_freeform_input() -> str:
    print()
    while True:
        raw = input("  Your response: ").strip()
        if raw:
            return raw
        print("  Please enter a response.")


# ── Game loop ─────────────────────────────────────────────────────────────────

def run_game() -> None:
    display_start_screen(scenario=get_active_scenario())

    if _mode == "freeform":
        console.print(
            "  [dim italic]Freeform mode — crises are generated by AI. "
            "Type your response in plain language.[/dim italic]\n"
        )

    input("  [Press Enter to begin your tenure...]\n")

    state = initialize_game({})

    # Pre-turn: load first crisis
    if _mode == "freeform":
        state = pre_freeform_graph.invoke(state)
    else:
        state = pre_classic_graph.invoke(state)

    while state["game_status"] == "active":
        # Display current turn and get player decision
        if _mode == "freeform":
            display_freeform_turn_screen(state)
            player_text = _get_freeform_input()
            state["player_input"] = player_text
            state = post_freeform_graph.invoke(state)
            display_freeform_consequences(state)
        else:
            display_turn_screen(state)
            choice = _get_classic_choice(state)
            state["player_choice_index"] = choice
            state = post_classic_graph.invoke(state)
            display_consequences(state)

        # Win / loss check
        lost, reason = check_loss(
            state["national_stats"],
            state["faction_support"],
            state.get("economy_stats"),
        )
        if lost:
            state["game_status"] = "lost"
            state["loss_reason"]  = reason
            break

        if state["current_turn"] > state["max_turns"]:
            state["game_status"] = "won"
            end_state, _ = determine_end_state(
                state["national_stats"],
                state["faction_support"],
                state.get("economy_stats"),
            )
            state["end_state"] = end_state
            break

        # Pre-turn: load next crisis
        if _mode == "freeform":
            state = pre_freeform_graph.invoke(state)
        else:
            state = pre_classic_graph.invoke(state)

    # generate_end_summary returns a partial dict — merge into full state
    state = {**state, **generate_end_summary(state)}

    if state["game_status"] == "lost":
        display_loss_screen(state)

    display_end_screen(state)
    console.print("\n  Thanks for playing. Veridia endures.\n")


if __name__ == "__main__":
    run_game()
